"""Outcome of a winning payline inside a spin"""

from dataclasses import dataclass
from decimal import Decimal

from slot_engine.domain.payline import Payline
from slot_engine.domain.symbol import Symbol


@dataclass(frozen=True, slots=True)
class LineWin:
    """Individual prize generated by a payline

    Represents a certain winning payline, the `count` first
    reels (left to right) show the same `Symbol`, and the
    paytable assigned `payout` to thay combination

    Attributes:
        payline: line of pay that triggered the winning
        symbol: symbol that repeats consecutively from column 0
        count: Number of consecutives coincidences (>=1)
        payout: Multiplier of the prize
    """

    payline: Payline
    symbol: Symbol
    count: int
    payout: Decimal

    def __post_init__(self) -> None:
        if self.count <= 0:
            raise ValueError("LineWin count must be positive")
        if self.count > self.payline.length:
            raise ValueError(
                f"LineWin count ({self.count}) exceeds payline length ({self.payline.length})"
            )
        if self.payout < Decimal("0"):
            raise ValueError("LineWin payout cannot be negative")

    def describe(self) -> str:
        """Description of prize, useful for logs and audits"""
        return f"{self.payline.name}: {self.count}x {self.symbol.name} -> {self.payout} "
